do $$
begin
  if not exists (select 1 from pg_type where typname = 'banco_tipo') then
    create type public.banco_tipo as enum ('CORRENTE', 'POUPANCA', 'CAIXA', 'CARTAO', 'INVESTIMENTO', 'OUTRO');
  end if;
end
$$;

create table if not exists public.transaction_categories (
  id integer generated always as identity not null,
  nome text not null,
  descricao text null,
  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint transaction_categories_pkey primary key (id),
  constraint transaction_categories_nome_key unique (nome)
);

create table if not exists public.bank_accounts (
  id bigint generated by default as identity not null,
  titulo text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  valor_inicial numeric(14, 2) not null default 0,
  agencia text null,
  conta_numero text null,
  tipo public.banco_tipo not null default 'CORRENTE'::public.banco_tipo,
  proprietario text null,
  ativo boolean not null default true,
  constraint bank_accounts_pkey primary key (id),
  constraint bank_accounts_titulo_key unique (titulo)
);

create table if not exists public.payment_methods (
  id integer generated always as identity not null,
  nome text not null,
  codigo text not null default 'OUTRO',
  descricao text null,
  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint payment_methods_pkey primary key (id),
  constraint payment_methods_nome_key unique (nome)
);

alter table public.transaction_categories enable row level security;
alter table public.bank_accounts enable row level security;
alter table public.payment_methods enable row level security;

drop policy if exists "Authenticated users can read transaction categories" on public.transaction_categories;
create policy "Authenticated users can read transaction categories"
on public.transaction_categories for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage transaction categories" on public.transaction_categories;
create policy "Authenticated users can manage transaction categories"
on public.transaction_categories for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can read bank accounts" on public.bank_accounts;
create policy "Authenticated users can read bank accounts"
on public.bank_accounts for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage bank accounts" on public.bank_accounts;
create policy "Authenticated users can manage bank accounts"
on public.bank_accounts for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can read payment methods" on public.payment_methods;
create policy "Authenticated users can read payment methods"
on public.payment_methods for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage payment methods" on public.payment_methods;
create policy "Authenticated users can manage payment methods"
on public.payment_methods for all
to authenticated
using (true)
with check (true);

insert into public.transaction_categories (nome, descricao)
select *
from (
  values
    ('NAO RELACIONADO', 'Categoria padrao para lancamentos sem classificacao'),
    ('VENDA DE VEICULO', 'Receitas provenientes de venda de veiculos'),
    ('MANUTENCAO', 'Despesas com manutencao e preparacao'),
    ('DOCUMENTACAO', 'Despesas com taxas, laudos e documentacao')
) as seed(nome, descricao)
where not exists (
  select 1 from public.transaction_categories c where c.nome = seed.nome
);

insert into public.payment_methods (nome, codigo, descricao)
select *
from (
  values
    ('Dinheiro', 'DINHEIRO', 'Pagamento em especie'),
    ('PIX', 'PIX', 'Transferencia instantanea'),
    ('Cartao de credito', 'CARTAO_CREDITO', 'Pagamento por credito'),
    ('Cartao de debito', 'CARTAO_DEBITO', 'Pagamento por debito'),
    ('Transferencia', 'TRANSFERENCIA', 'TED, DOC ou transferencia bancaria'),
    ('Boleto', 'BOLETO', 'Pagamento por boleto'),
    ('Cheque', 'CHEQUE', 'Pagamento por cheque'),
    ('Outro', 'OUTRO', 'Outro metodo de pagamento')
) as seed(nome, codigo, descricao)
where not exists (
  select 1 from public.payment_methods p where p.nome = seed.nome
);

insert into public.bank_accounts (titulo, valor_inicial, tipo)
select 'Caixa Geral', 0, 'CAIXA'::public.banco_tipo
where not exists (
  select 1 from public.bank_accounts b where b.titulo = 'Caixa Geral'
);

alter table public.transactions
  add column if not exists categoria_id integer null,
  add column if not exists banco_id bigint null,
  add column if not exists payment_method_id integer null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'transactions_categoria_id_fkey'
  ) then
    alter table public.transactions
      add constraint transactions_categoria_id_fkey
      foreign key (categoria_id) references public.transaction_categories (id)
      on update cascade;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'transactions_banco_id_fkey'
  ) then
    alter table public.transactions
      add constraint transactions_banco_id_fkey
      foreign key (banco_id) references public.bank_accounts (id)
      on update restrict;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'transactions_payment_method_id_fkey'
  ) then
    alter table public.transactions
      add constraint transactions_payment_method_id_fkey
      foreign key (payment_method_id) references public.payment_methods (id)
      on update cascade;
  end if;
end
$$;

create index if not exists idx_transactions_categoria_id on public.transactions using btree (categoria_id);
create index if not exists idx_transactions_banco_id on public.transactions using btree (banco_id);
create index if not exists idx_transactions_payment_method_id on public.transactions using btree (payment_method_id);

insert into public.permissions (slug, module, action, description)
select *
from (
  values
    ('types:view', 'types', 'view', 'Visualizar cadastros de tipos'),
    ('types:create', 'types', 'create', 'Criar cadastros de tipos'),
    ('types:update', 'types', 'update', 'Editar cadastros de tipos'),
    ('types:delete', 'types', 'delete', 'Excluir cadastros de tipos')
) as new_permissions(slug, module, action, description)
where not exists (
  select 1
  from public.permissions p
  where p.slug = new_permissions.slug
);

insert into public.role_permissions (role_name, permission_slug)
select 'Administrador', p.slug
from public.permissions p
where p.slug in ('types:view', 'types:create', 'types:update', 'types:delete')
and not exists (
  select 1
  from public.role_permissions rp
  where rp.role_name = 'Administrador'
    and rp.permission_slug = p.slug
);
