do $$
begin
  if not exists (select 1 from pg_type where typname = 'sale_status') then
    create type public.sale_status as enum ('PENDENTE', 'CONCLUIDA', 'CANCELADA');
  end if;

  if not exists (select 1 from pg_type where typname = 'sale_discount_type') then
    create type public.sale_discount_type as enum ('VALOR_FIXO', 'PERCENTUAL');
  end if;
end
$$;

create table if not exists public.sales (
  id bigint generated by default as identity not null,
  vehicle_id bigint not null,
  customer_id bigint not null,
  seller_id uuid null,
  status public.sale_status not null default 'PENDENTE',
  sale_date timestamp with time zone not null default now(),
  sub_total numeric(14, 2) not null,
  discount_type public.sale_discount_type null,
  discount_value numeric(14, 2) null default 0,
  total_value numeric(14, 2) not null,
  payment_method text null,
  fiscal_observations text null,
  commission_percent_applied numeric(5, 2) null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null,
  updated_by uuid null,
  canceled_at timestamp with time zone null,
  canceled_by uuid null,
  constraint sales_pkey primary key (id),
  constraint sales_vehicle_id_fkey foreign key (vehicle_id) references public.vehicles (id),
  constraint sales_customer_id_fkey foreign key (customer_id) references public.customers (id),
  constraint sales_seller_id_fkey foreign key (seller_id) references public.users (id),
  constraint sales_created_by_fkey foreign key (created_by) references public.users (id),
  constraint sales_updated_by_fkey foreign key (updated_by) references public.users (id),
  constraint sales_canceled_by_fkey foreign key (canceled_by) references public.users (id),
  constraint sales_total_value_check check (total_value >= 0),
  constraint sales_sub_total_check check (sub_total >= 0),
  constraint sales_discount_value_check check (discount_value is null or discount_value >= 0)
);

alter table public.sales
  add column if not exists canceled_at timestamp with time zone null,
  add column if not exists canceled_by uuid null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'sales_canceled_by_fkey'
  ) then
    alter table public.sales
      add constraint sales_canceled_by_fkey foreign key (canceled_by) references public.users (id);
  end if;
end
$$;

create index if not exists idx_sales_vehicle_id on public.sales using btree (vehicle_id);
create index if not exists idx_sales_customer_id on public.sales using btree (customer_id);
create index if not exists idx_sales_seller_id on public.sales using btree (seller_id);
create index if not exists idx_sales_status on public.sales using btree (status);
create index if not exists idx_sales_sale_date on public.sales using btree (sale_date desc);

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'transactions_venda_id_fkey'
  ) then
    alter table public.transactions
      add constraint transactions_venda_id_fkey foreign key (venda_id) references public.sales (id) not valid;
  end if;
end
$$;

alter table public.sales enable row level security;

drop policy if exists "Authenticated users can read sales" on public.sales;
create policy "Authenticated users can read sales"
on public.sales for select
to authenticated
using (
  exists (
    select 1
    from public.users u
    join public.profiles p on p.id = u.profile_id
    left join public.role_permissions rp on rp.role_name = p.name
    where u.id = auth.uid()
      and (p.name = 'Administrador' or rp.permission_slug in ('admin', 'sales:view', 'vehicles:view'))
  )
);

drop policy if exists "Authenticated users can insert sales" on public.sales;
create policy "Authenticated users can insert sales"
on public.sales for insert
to authenticated
with check (
  exists (
    select 1
    from public.users u
    join public.profiles p on p.id = u.profile_id
    left join public.role_permissions rp on rp.role_name = p.name
    where u.id = auth.uid()
      and (p.name = 'Administrador' or rp.permission_slug in ('admin', 'sales:create', 'vehicles:update'))
  )
);

drop policy if exists "Authenticated users can update sales" on public.sales;
create policy "Authenticated users can update sales"
on public.sales for update
to authenticated
using (
  exists (
    select 1
    from public.users u
    join public.profiles p on p.id = u.profile_id
    left join public.role_permissions rp on rp.role_name = p.name
    where u.id = auth.uid()
      and (p.name = 'Administrador' or rp.permission_slug in ('admin', 'sales:update', 'vehicles:update'))
  )
)
with check (
  exists (
    select 1
    from public.users u
    join public.profiles p on p.id = u.profile_id
    left join public.role_permissions rp on rp.role_name = p.name
    where u.id = auth.uid()
      and (p.name = 'Administrador' or rp.permission_slug in ('admin', 'sales:update', 'vehicles:update'))
  )
);

insert into public.permissions (slug, module, action, description)
select *
from (
  values
    ('sales:view', 'sales', 'view', 'Visualizar vendas'),
    ('sales:create', 'sales', 'create', 'Criar vendas'),
    ('sales:update', 'sales', 'update', 'Editar vendas'),
    ('sales:delete', 'sales', 'delete', 'Cancelar vendas')
) as new_permissions(slug, module, action, description)
where not exists (
  select 1
  from public.permissions p
  where p.slug = new_permissions.slug
);

insert into public.role_permissions (role_name, permission_slug)
select 'Administrador', p.slug
from public.permissions p
where p.slug in ('sales:view', 'sales:create', 'sales:update', 'sales:delete')
and not exists (
  select 1
  from public.role_permissions rp
  where rp.role_name = 'Administrador'
    and rp.permission_slug = p.slug
);
