do $$
begin
  if not exists (select 1 from pg_type where typname = 'customer_person_type') then
    create type public.customer_person_type as enum ('PF', 'PJ');
  end if;

  if not exists (select 1 from pg_type where typname = 'customer_status') then
    create type public.customer_status as enum ('ATIVO', 'INATIVO');
  end if;

  if not exists (select 1 from pg_type where typname = 'customer_rank') then
    create type public.customer_rank as enum ('LEAD', 'BRONZE', 'PRATA', 'OURO', 'VIP');
  end if;
end
$$;

create table if not exists public.customers (
  id bigint generated by default as identity not null,
  person_type public.customer_person_type not null,
  cpf_cnpj text not null,
  name text not null,
  email text not null,
  phone text not null,
  address text null,
  address_number text null,
  address_complement text null,
  neighborhood text null,
  city text not null,
  state text not null,
  zip_code text null,
  state_registration text null,
  municipal_registration text null,
  city_code text null,
  status public.customer_status not null default 'ATIVO',
  rank public.customer_rank null,
  ranked_by uuid null,
  ranked_at timestamp with time zone null,
  user_id uuid null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null,
  updated_by uuid null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  constraint customers_pkey primary key (id),
  constraint customers_user_id_key unique (user_id),
  constraint customers_email_key unique (email),
  constraint customers_cpf_cnpj_key unique (cpf_cnpj),
  constraint customers_user_id_fkey foreign key (user_id) references auth.users (id),
  constraint customers_created_by_fkey foreign key (created_by) references public.users (id),
  constraint customers_updated_by_fkey foreign key (updated_by) references public.users (id),
  constraint customers_deleted_by_fkey foreign key (deleted_by) references public.users (id),
  constraint customers_ranked_by_fkey foreign key (ranked_by) references public.users (id),
  constraint customers_email_format_chk check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

create index if not exists idx_customers_cpf_cnpj on public.customers using btree (cpf_cnpj);
create index if not exists idx_customers_status on public.customers using btree (status);
create index if not exists idx_customers_is_deleted on public.customers using btree (is_deleted);
create index if not exists idx_customers_user_id on public.customers using btree (user_id);

alter table public.customers enable row level security;

drop policy if exists "Authenticated users can read customers" on public.customers;
create policy "Authenticated users can read customers"
on public.customers for select
to authenticated
using (is_deleted = false);

drop policy if exists "Authenticated users can insert customers" on public.customers;
create policy "Authenticated users can insert customers"
on public.customers for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update customers" on public.customers;
create policy "Authenticated users can update customers"
on public.customers for update
to authenticated
using (true)
with check (true);

insert into public.permissions (slug, module, action, description)
select *
from (
  values
    ('customers:view', 'customers', 'view', 'Visualizar clientes'),
    ('customers:create', 'customers', 'create', 'Criar clientes'),
    ('customers:update', 'customers', 'update', 'Editar clientes'),
    ('customers:delete', 'customers', 'delete', 'Excluir clientes')
) as new_permissions(slug, module, action, description)
where not exists (
  select 1
  from public.permissions p
  where p.slug = new_permissions.slug
);

insert into public.role_permissions (role_name, permission_slug)
select 'Administrador', p.slug
from public.permissions p
where p.slug in ('customers:view', 'customers:create', 'customers:update', 'customers:delete')
and not exists (
  select 1
  from public.role_permissions rp
  where rp.role_name = 'Administrador'
    and rp.permission_slug = p.slug
);
