create table if not exists public.document_categories (
  id integer generated always as identity not null,
  nome text not null,
  descricao text null,
  ativo boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint document_categories_pkey primary key (id),
  constraint document_categories_nome_key unique (nome)
);

create table if not exists public.vehicle_documents (
  id bigint generated by default as identity not null,
  vehicle_id bigint not null,
  category_id integer null,
  title text not null,
  description text null,
  file_name text not null,
  file_path text not null,
  file_url text not null,
  file_size bigint null,
  mime_type text null,
  expires_at timestamp with time zone null,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null,
  updated_by uuid null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  constraint vehicle_documents_pkey primary key (id),
  constraint vehicle_documents_vehicle_id_fkey foreign key (vehicle_id) references public.vehicles (id) on delete cascade,
  constraint vehicle_documents_category_id_fkey foreign key (category_id) references public.document_categories (id) on update cascade,
  constraint vehicle_documents_created_by_fkey foreign key (created_by) references public.users (id),
  constraint vehicle_documents_updated_by_fkey foreign key (updated_by) references public.users (id),
  constraint vehicle_documents_deleted_by_fkey foreign key (deleted_by) references public.users (id)
);

create index if not exists idx_vehicle_documents_vehicle_id on public.vehicle_documents using btree (vehicle_id);
create index if not exists idx_vehicle_documents_category_id on public.vehicle_documents using btree (category_id);
create index if not exists idx_vehicle_documents_is_deleted on public.vehicle_documents using btree (is_deleted);

alter table public.document_categories enable row level security;
alter table public.vehicle_documents enable row level security;

drop policy if exists "Authenticated users can read document categories" on public.document_categories;
create policy "Authenticated users can read document categories"
on public.document_categories for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage document categories" on public.document_categories;
create policy "Authenticated users can manage document categories"
on public.document_categories for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can read vehicle documents" on public.vehicle_documents;
create policy "Authenticated users can read vehicle documents"
on public.vehicle_documents for select
to authenticated
using (is_deleted = false);

insert into public.document_categories (nome, descricao)
select *
from (
  values
    ('DOCUMENTO DO VEICULO', 'CRLV, DUT e documentos oficiais do veiculo'),
    ('COMPROVANTE', 'Comprovantes financeiros e recibos'),
    ('LAUDO', 'Laudos cautelares, vistorias e relatorios tecnicos'),
    ('CONTRATO', 'Contratos e termos assinados')
) as seed(nome, descricao)
where not exists (
  select 1 from public.document_categories c where c.nome = seed.nome
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vehicle-documents',
  'vehicle-documents',
  false,
  52428800,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into public.permissions (slug, module, action, description)
select *
from (
  values
    ('documents:view', 'documents', 'view', 'Visualizar anexos de veiculos'),
    ('documents:create', 'documents', 'create', 'Criar anexos de veiculos'),
    ('documents:update', 'documents', 'update', 'Editar anexos de veiculos'),
    ('documents:delete', 'documents', 'delete', 'Excluir anexos de veiculos')
) as new_permissions(slug, module, action, description)
where not exists (
  select 1
  from public.permissions p
  where p.slug = new_permissions.slug
);

insert into public.role_permissions (role_name, permission_slug)
select 'Administrador', p.slug
from public.permissions p
where p.slug in ('documents:view', 'documents:create', 'documents:update', 'documents:delete')
and not exists (
  select 1
  from public.role_permissions rp
  where rp.role_name = 'Administrador'
    and rp.permission_slug = p.slug
);
