do $$
begin
  if not exists (select 1 from pg_type where typname = 'metodo_pagamento') then
    create type public.metodo_pagamento as enum (
      'DINHEIRO',
      'PIX',
      'CARTAO_CREDITO',
      'CARTAO_DEBITO',
      'TRANSFERENCIA',
      'BOLETO',
      'CHEQUE',
      'OUTRO'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'tipos_transacao') then
    create type public.tipos_transacao as enum ('RECEITA', 'DESPESA');
  end if;
end
$$;

create table if not exists public.transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  descricao text not null,
  valor numeric(14, 2) not null,
  data timestamp with time zone not null default now(),
  metodo_pagamento public.metodo_pagamento not null,
  categoria text not null default 'NAO RELACIONADO'::text,
  tipo public.tipos_transacao not null,
  vehicle_id bigint null,
  venda_id bigint null,
  nome_pagador text not null,
  cpf_cnpj_pagador text not null,
  valor_liquido numeric(14, 2) null,
  pendente boolean not null default false,
  created_by uuid null,
  updated_by uuid null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  constraint transactions_pkey primary key (id),
  constraint transactions_vehicle_id_fkey foreign key (vehicle_id) references public.vehicles (id) on delete cascade,
  constraint transactions_created_by_fkey foreign key (created_by) references public.users (id),
  constraint transactions_updated_by_fkey foreign key (updated_by) references public.users (id),
  constraint transactions_deleted_by_fkey foreign key (deleted_by) references public.users (id)
);

create index if not exists idx_transactions_vehicle_id on public.transactions using btree (vehicle_id);
create index if not exists idx_transactions_venda_id on public.transactions using btree (venda_id);
create index if not exists idx_transactions_data on public.transactions using btree (data desc);
create index if not exists idx_transactions_tipo on public.transactions using btree (tipo);
create index if not exists idx_transactions_is_deleted on public.transactions using btree (is_deleted);

alter table public.transactions enable row level security;

drop policy if exists "Authenticated users can read transactions" on public.transactions;
create policy "Authenticated users can read transactions"
on public.transactions for select
to authenticated
using (is_deleted = false);

drop policy if exists "Authenticated users can insert transactions" on public.transactions;
create policy "Authenticated users can insert transactions"
on public.transactions for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update transactions" on public.transactions;
create policy "Authenticated users can update transactions"
on public.transactions for update
to authenticated
using (is_deleted = false)
with check (true);

insert into public.permissions (slug, module, action, description)
select *
from (
  values
    ('finance:view', 'finance', 'view', 'Visualizar fluxo de caixa'),
    ('finance:create', 'finance', 'create', 'Criar transacoes financeiras'),
    ('finance:update', 'finance', 'update', 'Editar transacoes financeiras'),
    ('finance:delete', 'finance', 'delete', 'Excluir transacoes financeiras')
) as new_permissions(slug, module, action, description)
where not exists (
  select 1
  from public.permissions p
  where p.slug = new_permissions.slug
);

insert into public.role_permissions (role_name, permission_slug)
select 'Administrador', p.slug
from public.permissions p
where p.slug in ('finance:view', 'finance:create', 'finance:update', 'finance:delete')
and not exists (
  select 1
  from public.role_permissions rp
  where rp.role_name = 'Administrador'
    and rp.permission_slug = p.slug
);
