create table if not exists public.transaction_attachments (
  id bigint generated by default as identity not null,
  transaction_id bigint not null,
  file_name text not null,
  file_path text not null,
  file_url text not null,
  file_size bigint null,
  mime_type text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  created_by uuid null,
  updated_by uuid null,
  is_deleted boolean not null default false,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  constraint transaction_attachments_pkey primary key (id),
  constraint transaction_attachments_transaction_id_fkey foreign key (transaction_id) references public.transactions (id) on delete cascade,
  constraint transaction_attachments_created_by_fkey foreign key (created_by) references public.users (id),
  constraint transaction_attachments_updated_by_fkey foreign key (updated_by) references public.users (id),
  constraint transaction_attachments_deleted_by_fkey foreign key (deleted_by) references public.users (id)
);

create index if not exists idx_transaction_attachments_transaction_id on public.transaction_attachments using btree (transaction_id);
create index if not exists idx_transaction_attachments_is_deleted on public.transaction_attachments using btree (is_deleted);

alter table public.transaction_attachments enable row level security;

drop policy if exists "Authenticated users can read transaction attachments" on public.transaction_attachments;
create policy "Authenticated users can read transaction attachments"
on public.transaction_attachments for select
to authenticated
using (is_deleted = false);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'transaction-attachments',
  'transaction-attachments',
  false,
  52428800,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
